#!/bin/bash
# Generate terraform.tfvars values for GitHub Runners on AWS
# Usage: ./scripts/generate-tfvars.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/../terraform.tfvars"

echo "=================================================="
echo "GitHub Runners - Terraform Variables Generator"
echo "=================================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# -----------------------------------------------------------------------------
# AWS Configuration
# -----------------------------------------------------------------------------
echo -e "${YELLOW}1. AWS Configuration${NC}"
echo "-------------------"

# Get default region
AWS_REGION=$(aws configure get region 2>/dev/null || echo "us-east-1")
echo -e "aws_region = \"${GREEN}${AWS_REGION}${NC}\""

# Get default VPC
echo ""
echo "Fetching default VPC..."
VPC_ID=$(aws ec2 describe-vpcs \
    --filters "Name=is-default,Values=true" \
    --query "Vpcs[0].VpcId" \
    --output text 2>/dev/null || echo "")

if [ -z "$VPC_ID" ] || [ "$VPC_ID" == "None" ]; then
    echo -e "${YELLOW}No default VPC found. Listing all VPCs:${NC}"
    aws ec2 describe-vpcs --query "Vpcs[*].[VpcId,Tags[?Key=='Name'].Value|[0]]" --output table
    echo ""
    VPC_ID="REPLACE_WITH_YOUR_VPC_ID"
    echo -e "${RED}Set vpc_id manually in terraform.tfvars${NC}"
else
    echo -e "vpc_id = \"${GREEN}${VPC_ID}${NC}\""
fi

# Get subnets
echo ""
echo "Fetching subnets..."
if [ "$VPC_ID" != "REPLACE_WITH_YOUR_VPC_ID" ]; then
    SUBNET_IDS=$(aws ec2 describe-subnets \
        --filters "Name=vpc-id,Values=${VPC_ID}" \
        --query "Subnets[*].SubnetId" \
        --output json 2>/dev/null || echo '["REPLACE_WITH_SUBNET_IDS"]')
    echo -e "subnet_ids = ${GREEN}${SUBNET_IDS}${NC}"
else
    SUBNET_IDS='["REPLACE_WITH_SUBNET_IDS"]'
    echo "Set subnet_ids manually after selecting VPC"
fi

# -----------------------------------------------------------------------------
# GitHub Webhook Secret
# -----------------------------------------------------------------------------
echo ""
echo -e "${YELLOW}2. GitHub Webhook Secret${NC}"
echo "------------------------"
WEBHOOK_SECRET=$(openssl rand -hex 32)
echo -e "github_webhook_secret = \"${GREEN}${WEBHOOK_SECRET}${NC}\""
echo ""
echo -e "${RED}SAVE THIS SECRET - you'll need it when configuring the GitHub App webhook${NC}"

# -----------------------------------------------------------------------------
# Write terraform.tfvars
# -----------------------------------------------------------------------------
cat > "${OUTPUT_FILE}" << EOF
# Generated by generate-tfvars.sh on $(date)
# GitHub Runners on AWS - Terraform Variables

aws_region  = "${AWS_REGION}"
environment = "prod"

# AWS Networking
vpc_id     = "${VPC_ID}"
subnet_ids = ${SUBNET_IDS}

# GitHub App Configuration
# Create app at: https://github.com/settings/apps/new (personal)
#            or: https://github.com/organizations/YOUR_ORG/settings/apps/new (org)
github_app_id         = "REPLACE_WITH_APP_ID"
github_app_key_base64 = "REPLACE_WITH_BASE64_KEY"
github_webhook_secret = "${WEBHOOK_SECRET}"

# Runner Configuration
prefix = "github-runner"

linux_x64_max_runners   = 5
linux_arm64_max_runners = 5
windows_x64_max_runners = 3

enable_spot_instances = true

runner_extra_labels = []
EOF

# -----------------------------------------------------------------------------
# Print instructions
# -----------------------------------------------------------------------------
echo ""
echo -e "${YELLOW}3. GitHub App Setup Instructions${NC}"
echo "---------------------------------"
echo ""
echo "Create a GitHub App at:"
echo -e "  ${GREEN}https://github.com/settings/apps/new${NC} (personal)"
echo -e "  ${GREEN}https://github.com/organizations/YOUR_ORG/settings/apps/new${NC} (org)"
echo ""
echo "Required Settings:"
echo "  - App name: github-runners-aws (or unique name)"
echo "  - Homepage URL: https://github.com/your-org"
echo "  - Webhook URL: (output after terraform apply)"
echo "  - Webhook secret: ${WEBHOOK_SECRET}"
echo ""
echo "Required Permissions:"
echo "  Repository:"
echo "    - Actions: Read-only"
echo "    - Administration: Read & write"
echo "    - Checks: Read-only"
echo "    - Metadata: Read-only"
echo "  Organization (if using org runners):"
echo "    - Self-hosted runners: Read & write"
echo ""
echo "Subscribe to events:"
echo "    - Workflow job"
echo ""
echo -e "${YELLOW}4. After Creating the GitHub App${NC}"
echo "---------------------------------"
echo ""
echo "a) Get App ID from the app's settings page"
echo ""
echo "b) Generate private key and base64 encode it:"
echo -e "   ${GREEN}base64 -i ~/Downloads/your-app.private-key.pem | tr -d '\\n'${NC}"
echo ""
echo "c) Update terraform.tfvars with:"
echo "   - github_app_id"
echo "   - github_app_key_base64"
echo ""
echo "=================================================="
echo -e "${GREEN}Written to: ${OUTPUT_FILE}${NC}"
echo "=================================================="
echo ""
cat "${OUTPUT_FILE}"
echo ""
echo "=================================================="
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Create GitHub App with settings above"
echo "  2. Update github_app_id and github_app_key_base64 in terraform.tfvars"
echo "  3. Run: terraform init && terraform plan"
echo "=================================================="
